name: Build Test

on:
  push:
    branches:
      - feature/cicd
  pull_request:
    branches:
      - feature/cicd

jobs:
  docker:
    name: Docker on premises
    timeout-minutes: 10
    runs-on: [self-hosted, macOS, X64]
    env:
      ECG_AU_DIR: ${{ secrets.EcgAuDir }}
      SQLITE_ABS_DIR: ${{ secrets.SqliteAbsDir }}

    steps:
    - uses: actions/checkout@v2

    - name: Docker Compose Up
      run: docker-compose up --build -d
