name: Build Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: Docker on premises
    timeout-minutes: 10
    runs-on: [self-hosted, linux, X64]
    env:
      ECG_AU_DIR: /home/wellysis-tft/Desktop/pipeline/au-db/AU  # ${{ secrets.EcgAuDir }}
      SQLITE_ABS_DIR: /home/wellysis-tft/Desktop/code/ecg-viewer-proto/back-end/sqlite.db  # ${{ secrets.SqliteAbsDir }}

    steps:
    - uses: actions/checkout@v2

    - name: Docker Compose Up
      run: docker-compose up --build -d
